steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/extreme-passkey-420309/my-node-app", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/extreme-passkey-420309/my-node-app"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "my-node-app",
        "--image",
        "gcr.io/extreme-passkey-420309/my-node-app",
        "--platform",
        "managed",
        "--region",
        "us-central1",
      ]
images:
  - "gcr.io/extreme-passkey-420309/my-node-app"
